# Generated by Django 5.2.5 on 2025-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0002_sme_alter_task_sme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sme_old',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
