# Generated by Django 5.2.5 on 2025-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0003_task_sme_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject Matter Expert / Engineering'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='sme_old',
        ),
        migrations.DeleteModel(
            name='SME',
        ),
    ]
