# Generated by Django 5.2.5 on 2025-08-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0004_alter_task_sme_remove_task_sme_old_delete_sme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='sme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='online_help.sme'),
        ),
    ]
