# Generated by Django 5.2.5 on 2025-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0005_sme_alter_task_sme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.CharField(default='0%', max_length=20),
        ),
    ]
