# Generated by Django 5.2.5 on 2025-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0006_version_task_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('grey', 'Grey'), ('white', 'White'), ('orange', 'Orange')], default='white', max_length=20),
        ),
    ]
