# Generated by Django 5.2.5 on 2025-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0007_alter_task_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completion',
        ),
        migrations.AddField(
            model_name='subsection',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('grey', 'Grey'), ('white', 'White'), ('orange', 'Orange')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='subsection',
            name='completion',
            field=models.CharField(default='0%', max_length=20),
        ),
    ]
