# Generated by Django 5.2.5 on 2025-08-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0008_remove_task_color_remove_task_completion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.AddField(
            model_name='subsection',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
