# Generated by Django 5.2.5 on 2025-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_help', '0009_remove_task_comments_subsection_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='writer',
        ),
        migrations.AddField(
            model_name='task',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='online_help.writer'),
        ),
    ]
